services:
  - type: web
    name: loterie-fdj-backend
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health

